# Generated by Django 5.0.2 on 2024-04-12 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlenAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('intro', models.CharField(max_length=1000, verbose_name='介绍')),
                ('is_hot', models.BooleanField(verbose_name='是否热门')),
            ],
            options={
                'db_table': 'tb_subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.BooleanField(default=True, verbose_name='性别')),
                ('birth', models.DateField(verbose_name='出生日期')),
                ('intro', models.CharField(max_length=1000, verbose_name='个人介绍')),
                ('photo', models.ImageField(max_length=255, upload_to='', verbose_name='照片')),
                ('good_count', models.IntegerField(db_column='gcount', default=0, verbose_name='好评数')),
                ('bad_count', models.IntegerField(db_column='bcount', default=0, verbose_name='差评数')),
            ],
            options={
                'db_table': 'tb_teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GlenAPP.question')),
            ],
        ),
    ]
